version: 0.2

env:
  secrets-manager:
    JENKINS_API_USERNAME: jenkins_config:JENKINS_API_USERNAME
    JENKINS_API_TOKEN: jenkins_config:JENKINS_API_TOKEN

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Installing AWSCLI for codeartifact authorization token
      - pip install awscli --upgrade --user 
  pre_build:
    commands:
      #- export STAMP="1.0-`date +%Y%m%d.%H%M%S`"
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain leohickstein-repository-manager --domain-owner 611095324135 --query authorizationToken --output text`
  build:
    commands:
      #- mvn --no-transfer-progress versions:set -DnewVersion=$STAMP
      - mvn --no-transfer-progress -s settings.xml clean package deploy
  post_build: 
    commands: 

artifacts:
  files:
    - target/*.jar
  name: hello-cicd-$(date +%Y-%m-%d) 

cache:
  paths:
    - "/root/.m2/**/*"
